<div class="jumbotron">
    <h1>Willkommen im <span class="zf-green">Kundenportal</span></h1>
    <div class="embed-responsive embed-responsive-16by9 hidden-xs">
		<p>&nbsp;</p>
		<iframe width="560" height="315" class="embed-responsive-item" src="//www.youtube.com/embed/1-nUfvM5I54" allowfullscreen></iframe>
	</div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Das Kundenportal</h3>
            </div>
            <div class="panel-body">
                <p>Seit dem Bestehen des Projektes ist es unsere Maxime, Ihre Anforderungen zur vollsten Zufriedenheit zu erfüllen.</p>
				<p>Aus diesem Grund haben wir nun dieses Kundenportal für Sie entworfen, um Ihnen einen noch komfortableren Zugang zu unseren Ressourcen zu schaffen.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Auftrag erstellen</h3>
            </div>
            <div class="panel-body">
                <p>Aufträge für unsere Fertigungsanlage nehmen wir rund um die Uhr auf folgender Seite entgegen.</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('auftrag', array('action' => 'add')); ?>">Auftrag erstellen &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Auftragsstatus prüfen</h3>
            </div>
            <div class="panel-body">
                <p>Selbstverständlich können Sie nach dem Erstellen Ihres Auftrags hier den aktuellen Status prüfen.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('auftrag', array('action' => 'state')); ?>">Auftragsstatus prüfen &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
