<div class="jumbotron">
    <h1>Willkommen im <span class="zf-green">Kundenportal</span></h1>
    <p>&nbsp;</p>
    <div class="embed-responsive embed-responsive-16by9">
	  <iframe width="560" height="315" class="embed-responsive-item" src="//www.youtube.com/embed/1-nUfvM5I54" allowfullscreen></iframe>
	</div>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Über uns</h3>
            </div>
            <div class="panel-body">
                <p>Wir sind das Team.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Auftrag erstellen</h3>
            </div>
            <div class="panel-body">
                <p>Aufträge für unsere Fertigungsanlage nehmen wir rund um die Uhr auf folgender Seite entgegen.</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('auftrag', array('action' => 'add')); ?>">Auftrag erstellen &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Auftragsstatus prüfen</h3>
            </div>
            <div class="panel-body">
                <p>Selbstverständlich können Sie nach dem Erstellen Ihres Auftrags hier den aktuellen Status prüfen.</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('auftrag', array('action' => 'state')); ?>">Auftragsstatus prüfen &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
